### ISSUE TITLE
Holyubofficial blocked

### ISSUE THREAD

**Issue by DJshelfmushroom** [holy-unblocker/website#1]
Are there other sites that could work? any alt sites? it says blocked for anonymous proxies so...

**Comment by DaSkoolMan** [comment]
This is your blocking problem 
Not holy unblocked 

You can use web view for example to unblock it or use sh1mmer

**Comment by DJshelfmushroom** [comment]
what are these things?

**Comment by powerCord1** [comment]
ye wasn't there like alternate links for incog.dev? i know one was floppa.net
does anyone know if there is any for holyub?
